[project]
name = "fastapi-zero"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "fastapi[standard]>=0.141.1",
    "pwdlib[argon2]>=0.3.1",
    "pyjwt>=2.13.0",
    "sqlalchemy[asyncio]>=2.0.51",
    "tzdata>=2026.3",
    "uvicorn>=0.52.1",
    "aiosqlite>=0.22.1",
]

[dependency-groups]
dev = [
    "poethepoet>=0.48.0",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.1",
    "typos>=1.49.0",
]

[tool.ruff]
line-length = 79
exclude = ['migrations']

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT', 'FAST']

[tool.ruff.format]
quote-style = 'single'

[tool.pytest.ini_options]
pythonpath = ['.']
addopts = ['-p', 'no:warnings', '--cov=.', '--cov-context=test', '--cov-branch', '--cov-report=term-missing',]
asyncio_default_fixture_loop_scope = 'function'

[tool.poe.tasks]
lint.sequence = [
    { cmd = "typos" },
    { cmd = "ruff check"},
]
format.sequence = [
    { cmd = "ruff check --fix" },
    { cmd = "ruff format" }
]
serve = "fastapi dev ./app.py"
test.sequence = [
    "lint",
    { cmd = "pytest -s -x -vv $POE_EXTRA_ARGS" },
    { cmd = "coverage html --show-contexts" },
]

[tool.poe]
poetry_command = ""

[tool.typos.files]
extend-exclude = ['*.md','migrations/**']

[tool.coverage.run]
core = "ctrace"
concurrency = ["thread", "greenlet"]